template: screwdriver-cd-test/test-pipeline-template@1.0.0
shared:
  image: node:20
  environment:
    BAR: "baz"

jobs:
  main:
    image: node:22
    environment:
      BAZ: "qux"
    annotations:
      screwdriver.cd/displayName: "foo-bar"

  test:
    image: node:23
    environment:
      QUX: "quux"
    annotations:
      screwdriver.cd/displayName: "baz-qux"
    steps:
      - pretest: echo 'pretest'
      - test: echo $QUX
      - posttest: echo 'posttest'
