template: screwdriver-cd-test/test-pipeline-template@latest
shared:
  image: node:20
  environment:
    BAR: "baz"

jobs:
  main:
    image: node:22
    environment:
      BAZ: "qux"
    annotations:
      screwdriver.cd/displayName: "foo-bar"